# Generated by Django 5.1.3 on 2025-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Certificate title or course name', max_length=200)),
                ('issuing_organization', models.CharField(help_text='e.g., Coursera, Udemy, AWS, etc.', max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no expiry', null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Certificate ID or credential number', max_length=200)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify certificate', max_length=500)),
                ('certificate_image', models.ImageField(blank=True, help_text='Upload certificate image', null=True, upload_to='certificates/')),
                ('description', models.TextField(blank=True, help_text='Additional details about the certificate')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order', '-issue_date'],
            },
        ),
    ]
